if: tag IS blank
os: linux
language: python
dist: xenial
env:
  global:
  - BUILD_PYTHON_VERSION=3.9.0
  - MIN_PYTHON_VERSION=3.9.0
  - BUILD_OPENSSL_VERSION=1.1.1h
  - MIN_OPENSSL_VERSION=1.1.1h
  - PATCHELF_VERSION=0.11
  - PYINSTALLER_COMMIT=1e571ae1a302709583667f41fbc2508b9a79a05f
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/python"
  - "$HOME/ssl"
jobs:
  include:
  - os: linux
    name: Linux 64-bit Xenial
    dist: xenial
    language: shell
  - os: osx
    name: MacOS 10.13
    language: generic
    osx_image: xcode10.1
  - os: windows
    name: Windows 64-bit
    language: shell
  - os: windows
    name: Windows 32-bit
    language: shell

before_install:
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then export MYOS="macos"; else export MYOS="${TRAVIS_OS_NAME}"; fi
- if [ "${TRAVIS_JOB_NAME}" == "Windows 32-bit" ]; then export PLATFORM="x86"; elif
  [ "${TRAVIS_CPU_ARCH}" == "amd64" ]; then export PLATFORM="x86_64"; else export
  PLATFORM="${TRAVIS_CPU_ARCH}"; fi
- source travis/${TRAVIS_OS_NAME}-before-install.sh

install:
- source travis/${TRAVIS_OS_NAME}-install.sh

script:
- chrome-bisect/chrome-bisect --version

before_deploy:
- export TRAVIS_TAG="preview"

deploy:
  provider: releases
  api_key:
    secure: bFnQEDnLssV7HcAUPiuM7OBEClecMfTD7tSM8cyCzXOOjISkFk0z4JFhGOPBO27x1WWaZrED2WFE8oWQhDt2J1nXRqT0BRzAsix2Jg35WVbX+zzmVEd/S6qDddt9BuVh1s1ot7KYdVbJc87uUhrgFbHvFo3q1on7pffpsRupJhBkrT9Kas2cC3RNoqDEiqzXPDMcboMbaf9egujo2bq+4W643Mar9HRJcY7XB5vaEc055PR+1ZN7XsM4IiARzgru4JVJGqcIdQYHOTbhssy9rrR9vSoFFjObAMIIcMJVEwODrfKOabiz9vmdHobi2sc/Vucq+a05jA0JqRFoyR02fJQSbyw7xJ2wFAAvd5OylvcJ2CKTQsu+0vX0IxdfZjjIGpDZJbQzeAL4s84rTsbhgYdGs1LKuzA7/7pMaz6s4S9b9jqjPDsBEdOQpy2NISRTynUePFzxvA3YtEVHzWWl/rBjbWnM8+KNlGAL3gDXBDxWZvDwCP8byOad5IGyTfrwiXk6rvXoeCxF2TFHXWs6LtINjDCOGMXMEnELE0LMHIN8l7IzcnFhdq8nBeWzCW5CFeI1MelGE/tu4+nEOLy+WtveL2zvFGETIj7JuDcCTUwn9QOWI1S4w3abizaHcBXJSzJ6dOZVzBzjBKQRXSsDgnH6RDIUut72U9D66YWda54=
  file: chrome-bisect-$CBVERSION-*
  file_glob: true
  overwrite: true
  skip_cleanup: true
  draft: true
  on:
    repo: jay0lee/chrome-bisect
