name: Build Chrome Bisect Script

on:
  push:
  pull_request:
  schedule:
    - cron: '30 20 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        include:
          - os: ubuntu-18.04
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - run: python3 -V
      
      - name: Install PyInstaller
        run: pip3 install pyinstaller
        
      - name: Install requirements
        run: pip3 install -r requirements.txt
        
      - name: Download bisect script
        run: curl -s --basic -n "https://chromium.googlesource.com/chromium/src/+/master/tools/bisect-builds.py?format=TEXT" | base64 -d > bisect-builds.py
        
      - name: Compile bisect script
        run: pyinstaller -F bisect-builds.py
      
      - name: Env vars
        run: set
  
      - name: Rename Linix binary
        run: mv dist/bisect-builds chrome-bisect-macos
        if: matrix.os == 'ubuntu-18.04'

      - name: Rename MacOS binary
        run: mv dist/bisect-builds chrome-bisect-linux
        if: matrix.os == 'macos-latest'

      - name: Rename Windows binary
        run: mv dist/bisect-builds.exe  chrome-bisect-windows.exe
        if: matrix.os == 'windows-latest'
        
      - name: Run binary
        run: |
          ./chrome-bisect-* --help
          pwd

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        if: matrix.os != 'windows-latest' # Mac/Linux upload
        with:
          name: chrome-bisect-${{ matrix.os }}
          path: |
            chrome-bisect-*
          
      - name: Download artifacts
        if: matrix.os == 'windows-latest' # Windows download
        uses: actions/download-artifact@v2
        with:
          path: ~/chrome-bisect/chrome-bisect/

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: matrix.os == 'windows-latest' # Windows runs last and uploads release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: false
          title: "Chrome Bisect"
          files: |
            chrome-bisect-*
