name: Build Chrome Bisect Script

on:
  push:
  pull_request:
  schedule:
    - cron: '30 20 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        include:
          - os: ubuntu-18.04
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - run: python3 -V
      
      - name: Install PyInstaller
        run: pip3 install pyinstaller
        
      - name: Install requirements
        run: pip3 install -r requirements.txt
        
      - name: Download bisect script
        run: curl -s --basic -n "https://chromium.googlesource.com/chromium/src/+/master/tools/bisect-builds.py?format=TEXT" | base64 -d > bisect-builds.py
        
      - name: Compile bisect script
        run: |
          pyinstaller --distpath chrome-bisect --name chrome-bisect bisect-builds.py
          chrome-bisect/chrome-bisect --help
          case "$(uname)" in
            "Linux") os=linux;;
            "Darwin") os=macos;;
            *) os=windows;;
          esac
          zip -r "chrome-bisect-${os}.zip" chrome-bisect/chrome-bisect

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        if: matrix.os != 'windows-latest' # Mac/Linux upload
        with:
          name: chrome-bisect-${{ matrix.os }}
          path: |
            chrome-bisect-*.zip

      - name: Download artifacts
        if: matrix.os == 'windows-latest' # Windows download
        uses: actions/download-artifact@v2
        
      - name: Set datetime version string
        if: matrix.os == 'windows-latest'
        id: dateversion
        run: |
          echo "::set-output name=dateversion::$(date +'%Y%m%d.%k%M%S')"

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: matrix.os == 'windows-latest'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.dateversion.outputs.dateversion }}
          prerelease: false
          draft: false
          title: "Chrome Bisect ${{ steps.dateversion.outputs.dateversion }}"
          files: |
            chrome-bisect-windows.zip
            chrome-bisect-macos-latest/*
            chrome-bisect-ubuntu-18.04/*
